// Generated by gencpp from file malish/Diode.msg
// DO NOT EDIT!


#ifndef MALISH_MESSAGE_DIODE_H
#define MALISH_MESSAGE_DIODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace malish
{
template <class ContainerAllocator>
struct Diode_
{
  typedef Diode_<ContainerAllocator> Type;

  Diode_()
    : red(0)
    , green(0)
    , blue(0)  {
    }
  Diode_(const ContainerAllocator& _alloc)
    : red(0)
    , green(0)
    , blue(0)  {
  (void)_alloc;
    }



   typedef int16_t _red_type;
  _red_type red;

   typedef int16_t _green_type;
  _green_type green;

   typedef int16_t _blue_type;
  _blue_type blue;





  typedef boost::shared_ptr< ::malish::Diode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::malish::Diode_<ContainerAllocator> const> ConstPtr;

}; // struct Diode_

typedef ::malish::Diode_<std::allocator<void> > Diode;

typedef boost::shared_ptr< ::malish::Diode > DiodePtr;
typedef boost::shared_ptr< ::malish::Diode const> DiodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::malish::Diode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::malish::Diode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace malish

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'malish': ['/home/user/catkin_ws/src/malish/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::malish::Diode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::malish::Diode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::malish::Diode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::malish::Diode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::malish::Diode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::malish::Diode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::malish::Diode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a530e893cf8706bc8d67c5b969d07eb5";
  }

  static const char* value(const ::malish::Diode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa530e893cf8706bcULL;
  static const uint64_t static_value2 = 0x8d67c5b969d07eb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::malish::Diode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "malish/Diode";
  }

  static const char* value(const ::malish::Diode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::malish::Diode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 red\n\
int16 green\n\
int16 blue\n\
";
  }

  static const char* value(const ::malish::Diode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::malish::Diode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.green);
      stream.next(m.blue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Diode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::malish::Diode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::malish::Diode_<ContainerAllocator>& v)
  {
    s << indent << "red: ";
    Printer<int16_t>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<int16_t>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<int16_t>::stream(s, indent + "  ", v.blue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MALISH_MESSAGE_DIODE_H
